FROM node:18 AS build

WORKDIR /app

COPY InvestimentSimulatorClient/package.json ./

RUN npm install -g npm@10.2.4

RUN npm install --force

COPY InvestimentSimulatorClient/ .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
